name: Playwright Tests

on:
  push:
    branches: [dev]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4] # Shard indices remain 1, 2, 3, 4
        shardTotal: [4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Load and Parse YAML File
        id: load_yaml
        run: |
          yaml_content=$(< .github/workflows/test_mapping.yml)
          echo "::set-output name=yamlContent::$yaml_content"

      - name: Run Playwright tests
        id: playwright_tests
        run: |
          shard_config=$(< .github/workflows/test_mapping.yml)
          echo "Value of shard_config:"
          echo "$shard_config"

          shard_index=${{ matrix.shardIndex }}
          shard_tests=$(echo "$shard_config" | jq -r ".shards[$shard_index - 1].tests | .[]")
          echo "Shard tests for shard $shard_index:"
          echo "$shard_tests"
          
          # Debugging: Print the value of shard_tests
          echo "Value of shard_tests: $shard_tests"
          
          # Iterate over each test file and execute it
          for test_file in $shard_tests; do
            echo "Running test file: $test_file"
            echo "Node.js version: $(node --version)"
            echo "Playwright version: $(npx playwright --version)"
            npx playwright test $test_file --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} | tee executed_tests_shard_${{ matrix.shardIndex }}.txt
          done



      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
