name: Run Playwright Tests

on:
  push:
    branches: [main]

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shardIndex: [1, 2, 3, 4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npm install playwright

      - name: Load and Parse YAML File
        id: load_yaml
        run: |
          yaml_content=$(<.github/workflows/test_mapping.yml)
          echo "::set-output name=yamlContent::$yaml_content"

      - name: Debug shard configuration
        run: |
          echo "Loaded YAML content:"
          echo "${{ steps.load_yaml.outputs.yamlContent }}"

      - name: Run Playwright tests
        run: |
          shard_config=$(echo "${{ steps.load_yaml.outputs.yamlContent }}")
          shard_index=${{ matrix.shardIndex }}
          shard_tests=$(echo "$shard_config" | yq eval ".shards[$shard_index].tests | .[]" -)
          echo "Shard tests for shard $shard_index:"
          echo "$shard_tests"
          # Execute tests for the current shard
          npx playwright test $shard_tests
