name: Playwright Tests

on:
  push:
    branches: [dev]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  playwright-tests:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4

      - name: Install js-yaml
        run: npm install js-yaml

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

     

      - name: Load and Parse JSON File
        id: load_json
        run: |
          echo "JSON_CONTENT: $JSON_CONTENT"  # Debugging: print JSON_CONTENT
          echo "$JSON_CONTENT" > tests/e2e/shard-json.json
          echo "File content:"
          cat tests/e2e/shard-json.json  # Debugging: print file content
          shard_index=${{ matrix.shardIndex }}
          shard_tests=$(node -e "const data = require('./tests/e2e/shard-json.json'); console.log(data.shards['$shard_index'].tests.join(' '));")
          echo "::set-output name=shardTests::$shard_tests"



      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
