name: Playwright Tests

on:
  push:
    branches: [dev]

jobs:
  playwright-tests:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4] # Shard indices remain 1, 2, 3, 4
        shardTotal: [4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Load YAML content
        id: load_yaml
        run: |
          yaml_content=$(cat .github/workflows/test_mapping.yml)
          echo "YAML Content:"
          echo "$yaml_content"
          echo "::set-output name=yamlContent::$yaml_content"

      - name: Parse YAML content
        id: parse_yaml
        run: |
          shard_index=${{ matrix.shardIndex }}
          echo "Parsing YAML content..."
          echo "YAML Content:"
          echo "${{ steps.load_yaml.outputs.yamlContent }}"
          shard_tests=$(echo "${{ steps.load_yaml.outputs.yamlContent }}" | awk '/shards:/{f=1} f && /tests:/{f=0} f && /- /{print}' | awk -v idx=$shard_index 'NR==idx')
          echo "Extracted tests for shard $shard_index:"
          echo "$shard_tests"
          echo "::set-output name=shardTests::$shard_tests"

      - name: Check parsed YAML output
        run: |
          echo "Parsed YAML output:"
          echo "${{ steps.parse_yaml.outputs.shardTests }}"

      - name: Run Playwright tests
        id: playwright_tests
        run: |
          shard_tests="${{ steps.parse_yaml.outputs.shardTests }}"
          echo "Shard tests for shard ${{ matrix.shardIndex }}:"
          echo "$shard_tests"
          npx playwright test $shard_tests --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} | tee executed_tests_shard_${{ matrix.shardIndex }}.txt

      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
