name: Playwright Tests

on:
  push:
    branches: [dev]

jobs:
  playwright-tests:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4] # Shard indices remain 1, 2, 3, 4
        shardTotal: [4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install js-yaml
        run: npm install js-yaml

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Install yq
        run: |
          sudo add-apt-repository ppa:rmescandon/yq -y
          sudo apt update
          sudo apt install yq -y

      - name: Load and Parse YAML File
        id: load_and_parse_yaml
        run: |
          shard_index=${{ matrix.shardIndex }}
          yaml_content=$(< .github/workflows/test_mapping.yml)
          shard_tests=$(echo "$yaml_content" | yq ".shards[$shard_index].tests" | tr -d '[]"' | tr ',' '\n')
          echo "Extracted tests:"
          echo "$shard_tests"
          echo "::set-output name=shardTests::$shard_tests"

      - name: Check parsed YAML output
        run: |
          echo "Parsed YAML output:"
          echo "${{ steps.load_and_parse_yaml.outputs.shardTests }}"



      - name: Run Playwright tests
        id: playwright_tests
        run: |
          shard_tests="${{ steps.load_and_parse_yaml.outputs.shardTests }}"
          echo "Shard tests for shard ${{ matrix.shardIndex }}:"
          echo "$shard_tests"
          npx playwright test $shard_tests --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} | tee executed_tests_shard_${{ matrix.shardIndex }}.txt

      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
