name: Playwright Tests
on:
  push:
    branches: [dev]
jobs:
  playwright-tests:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install js-yaml
        run: npm install js-yaml

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Read test mapping
        id: read_mapping
        run: |
          echo "::set-output name=mapping::$(cat .github/workflows/test_mapping.yml)"s

      - name: Determine tests for shard
        id: determine_tests
        run: |
          shard_index=${{ matrix.shardIndex }}
          yaml_data="${{ steps.read_mapping.outputs.mapping }}"
          echo "YAML data: $yaml_data"  # Add this line for debugging
          test_mapping=$(echo "$yaml_data" | node -e "const yaml = require('js-yaml'); const data = yaml.load(process.stdin); console.log('Parsed YAML data:', data); console.log('Shards:', data.shards); if (data.shards) { console.log('Tests for shard $((shard_index)):', data.shards[$((shard_index - 1))]?.tests.join(', ') || '


      - name: Run Playwright tests
        id: playwright_tests
        run: |
          tests="${{ steps.determine_tests.outputs.tests }}"
          npx playwright test $tests
      
      - name: Upload blob report to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1
